name: php-utils
services:
  appserver:
    type: php:custom
    via: cli
    overrides:
      build: ./config
      image: datalinx/php:7.4-php-utils
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  phpunit:
    service: appserver
    description: Run PHPUnit tests
    cmd: "/app/vendor/bin/phpunit"
