name: php-utils
services:
  appserver:
    type: php:custom
    via: cli
    webroot: .
    xdebug: "debug,coverage,develop"
    overrides:
      environment:
        # Support debugging CLI with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando
      build: ./config
      image: datalinx/php:8.1-php-utils
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  phpunit:
    service: appserver
    description: Run PHPUnit tests
    cmd: "/app/vendor/bin/phpunit"
